# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0005_employeeprofile_avg_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftsArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement', models.TextField(max_length=200)),
                ('submit_deadline', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Business')),
            ],
        ),
    ]
