# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_business_manager'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField()),
                ('subject', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('recipients', models.ManyToManyField(related_name='msg_receive', to='log.EmployeeProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_send', to='log.EmployeeProfile')),
            ],
        ),
    ]
