# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_business_manager'),
        ('core', '0003_broadcastmessage_employeerequest_shiftswapmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField()),
                ('subject', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Business')),
                ('recipients', models.ManyToManyField(related_name='manager_msg', to='log.EmployeeProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='business',
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
    ]
