# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170628_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftsarrangement',
            name='business',
        ),
        migrations.RemoveField(
            model_name='shiftswapmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='shiftswapmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ShiftsArrangement',
        ),
        migrations.DeleteModel(
            name='ShiftSwapMessage',
        ),
    ]
