# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shiftslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TmpHoliday',
            fields=[
                ('year', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('full_json', models.TextField()),
            ],
        ),
    ]
