# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170725_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='type',
            field=models.CharField(choices=[('P', 'Profile change'), ('S', 'Shift swap')], default='P', max_length=1),
        ),
    ]
