# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employeerequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftslot',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Holiday'),
        ),
    ]
