# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shiftslot_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TmpHoliday',
        ),
    ]
