# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_auto_20171030_1717'),
        ('core', '0014_shiftslot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.EmployeeProfile')),
                ('requested_slots', models.ManyToManyField(to='core.ShiftSlot')),
            ],
        ),
    ]
