# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shiftrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='requested_slots',
            field=models.ManyToManyField(related_name='slot_requests', to='core.ShiftSlot'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 18, 59, 7, 324230)),
        ),
    ]
