# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171112_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='submission_time',
            field=models.DateTimeField(),
        ),
    ]
