# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171112_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='type',
            field=models.CharField(choices=[('P', 'Profile change'), ('S', 'Shift swap'), ('M', 'Menu test retry'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
