# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171228_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='sent_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shiftslot',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047)], default=2018),
        ),
    ]
