# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180206_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 1, 13, 15, 788456)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='core.ShiftSlot'),
        ),
    ]
