# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180211_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 1, 16, 32, 387381)),
        ),
    ]
