# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180211_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='sent_time',
            field=models.DateTimeField(),
        ),
    ]
