# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180222_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
