# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180222_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='rank',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
