# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0032_business_logo'),
        ('core', '0031_auto_20180225_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_step', models.ImageField(choices=[(0, 'employee requested'), (1, 'employee accepted'), (2, 'manager accepted'), (-1, 'employee rejected'), (-2, 'manager rejected')], default=0, upload_to=b'')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SwapRequesting', to='log.EmployeeProfile')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SwapRequested', to='log.EmployeeProfile')),
            ],
        ),
    ]
