# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0033_employeeprofile_new_messages'),
        ('core', '0035_shiftswap_requested_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftswap',
            unique_together=set([('requester', 'requester_shift')]),
        ),
    ]
