# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180326_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswap',
            name='accept_step',
            field=models.IntegerField(choices=[(0, 'employee requested'), (1, 'employee accepted'), (2, 'manager accepted'), (-1, 'employee rejected'), (-2, 'manager rejected')], default=0),
        ),
    ]
