# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_shiftswap_employee_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswap',
            name='employee_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_request', to='core.EmployeeRequest'),
        ),
    ]
