# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180401_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftswap',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='shiftswap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
