# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180401_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('constraints', models.TextField(max_length=300)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='shiftslot',
            name='saved_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SavedSlot'),
        ),
    ]
