# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20180404_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedslot',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
