# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180404_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftslot',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
