# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180404_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermessage',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
