# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180414_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='total_tips',
            field=models.IntegerField(default=0),
        ),
    ]
