# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180420_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='requested_slots',
            field=models.ManyToManyField(blank=True, related_name='slot_requests', to='core.ShiftSlot'),
        ),
    ]
