# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20180421_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
