# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180421_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequest',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
