# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20180603_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerequest',
            options={'ordering': ['-sent_time']},
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='type',
            field=models.CharField(choices=[('P', 'Profile change'), ('S', 'Shift swap'), ('M', 'Menu test retry'), ('O', 'Other')], db_index=True, default='O', max_length=1),
        ),
    ]
