# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20180607_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='type',
            field=models.CharField(choices=[('P', 'Profile change'), ('S', 'Shift swap'), ('M', 'Menu test retry'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['type'], name='core_employ_type_606bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['status'], name='core_employ_status_90db2f_idx'),
        ),
    ]
