# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20170423_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
