# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_employeeprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avg_rate',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
