# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_business_tip_methos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='tip_methos',
            new_name='tip_method',
        ),
    ]
