# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_business_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='enable_mailing',
            field=models.BooleanField(default=True),
        ),
    ]
