# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20170629_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='curr_timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
