# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_business_curr_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='curr_timer',
            field=models.CharField(blank=True, choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=1, null=True),
        ),
    ]
