# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20170805_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='curr_timer',
        ),
        migrations.AddField(
            model_name='business',
            name='deadline_day',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=1, null=True),
        ),
    ]
