# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_auto_20170806_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='deadline_day',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default='7', max_length=1),
        ),
    ]
