# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_auto_20170812_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='start_slot_countdown',
            field=models.BooleanField(default=False),
        ),
    ]
