# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_auto_20170828_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='home_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
