# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_auto_20171113_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='menu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
