# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0024_employeeprofile_menu_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shift_generated',
            field=models.BooleanField(default=False),
        ),
    ]
