# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0025_business_shift_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='shift_generated',
            new_name='shifts_generated',
        ),
    ]
