# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0026_auto_20180211_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='shifts_generated',
            field=models.CharField(choices=[('0', 'Not generated'), ('1', 'Generated'), ('2', 'Failed'), ('3', 'Generating')], default='0', max_length=1),
        ),
    ]
