# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0027_auto_20180211_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='avg_rate',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
