# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_auto_20180225_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='ever_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
