# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0030_employeeprofile_arriving_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='arriving_method',
            field=models.CharField(choices=[('D', 'driving'), ('W', 'walking'), ('B', 'both')], default='D', max_length=1),
        ),
    ]
