# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0032_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
    ]
