# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0035_auto_20180420_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='preferred_shift_time_frames',
            field=models.TextField(blank=True, null=True),
        ),
    ]
