# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_auto_20180421_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='credentials_sent',
            field=models.BooleanField(default=False),
        ),
    ]
