# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='cool answer', max_length=100),
            preserve_default=False,
        ),
    ]
