# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_to_pass',
            field=models.IntegerField(default=10),
        ),
    ]
