# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_quiz_time_to_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
