# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_quiz_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_preview',
        ),
    ]
