# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_auto_20180421_0034'),
        ('menu', '0005_remove_quiz_is_preview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set([('business', 'role')]),
        ),
    ]
