# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20180603_1459'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='quiz',
            index_together=set([]),
        ),
    ]
